### ISSUE TITLE
Bug (or feature?): `CMSMenu.get_nodes()` returns URLs of unpublished pages

### ISSUE THREAD

**Issue by jrief** [django-cms/djangocms-versioning#387]
### How to reproduce:

* Start editing a page which is using a menu renderer.
* When calling `get_nodes` from `CMSMenu` all descendant pages are returned, even those which have never been published.

### Expected behaviour:

* When returning to the published view of a page, only published descendant pages are returned, this behaviour is also expected in edit mode.

The culprit is [this line of code](https://github.com/django-cms/djangocms-versioning/blob/8a4e6c99e1cd2540172abed12b20e1d6e1e90dc8/djangocms_versioning/cms_menus.py#L100C1-L101C1). In my opinion `states` should always be `[constants.PUBLISHED]`, because if someone edits a page, he might be confused to get a different menu structure compared to the published version of that page.

**Comment by fsbraun** [comment]
This is intentional. This allows navigation to not yet published pages using the menu when editing.

Note: The menu renderer of djangocms-versioning will be deprecated in the next version. It has performance issues. The core's menu renderer has been updated to work universally with and without versioning.

If you only want published pages also in edit mode, I suggest having a look here: https://github.com/django-cms/django-cms/blob/develop-4/cms/cms_menus.py

You can modify the if statement in lines 250ff. The default menus can be replaced, just like djangocms-versioning does replace them.

**Comment by fsbraun** [comment]
I close this issue since the `cms_menus.py` are deprecated.
