### ISSUE TITLE
Publishing a page shows form instead of reloading new content

### ISSUE THREAD

**Issue by jrief** [django-cms/djangocms-versioning#402]
There seems to be a regression in the sources making up `django-cms/cms/static/cms/js/dist/4.1.0/bundle.toolbar.min.js`. This bug is not visible yet to users installing django-cms from PyPI, but it will be as soon as we rebundle the JavaScript files.

How to reproduce:

* Check out the latest version from django-cms in branch `develop-4`.
* Bundle the Javascript sources: Run `gulp bundle`.
* Check out latest version from https://github.com/fsbraun/djangocms-versioning/tree/feat/timed-publication (the bug presumably also is reproducible with master from upstream).
* Open a page.
* Make the page editable, but do not edit anything.
* Publish the page. This will create a POST request such as `/de/admin/djangocms_versioning/pagecontentversion/45413/publish/` and works as expected, ie. the user sees the edited page again.
* Make the page editable again.
* Edit a plugin and save it.
* Publish the page. This now will create a GET request such as `/de/admin/djangocms_versioning/pagecontentversion/45413/publish/`. This opens a form with some time constraints and is not expeted.

By copying the latest bundled file from https://github.com/django-cms/django-cms/blob/develop-4/cms/static/cms/js/dist/4.1.0/bundle.toolbar.min.js to its local destination at `django-cms/cms/static/cms/js/dist/4.1.0/bundle.toolbar.min.js` this workflow works again as expected.

Conclusion:
* I assume that this is a regression somewhere in a JavaScript file.
* I also assume that when using the official main branch, then we get a permission denied, because of this [statement](https://github.com/django-cms/djangocms-versioning/blob/f726bc203c06ccbb8ba79dc9defb98d1b4e06a9d/djangocms_versioning/admin.py#L933
) (haven't tested yet).

**Comment by fsbraun** [comment]
@jrief That's an extremely interesting bug:
* djangocms-versioning loads a small `actions.js` into the toolbar that captures clicks on the publish button to send a post signal
* When adding a plugin, the toolbar is updated.
* While in 4.1.0 the toolbar is updated using DiffDOM, `develop-4` replaces it (this is due to a memory leak in an older version of DiffDOM)
* While the core's JS is reinitialized for the replaced toolbar, `actions.js` is not reloaded and the publish button issues a GET request

There are two issues here:
1. The toolbar officially can load JS and therefore preserve JS events if possible. This would be possible by going back to DIffDOM
2. The toolbar offers post requests for menu entries, but not for buttons. This is a missing functionality, since all things changing the database should use post requests.

The fix imho should address both issues.

**Comment by jrief** [comment]
I can test this on 2024-04-26. Thanks for the quick fix.

**Comment by fsbraun** [comment]
Yeah, the fix is not there yet ... I'll try.

**Comment by fsbraun** [comment]
@jrief I have built a first 4.1.1 release for testing including assets. You can test if this bug is sovled by installing `git+https://github.com/django-cms/django-cms@release/build`

**Comment by jrief** [comment]
From a functional point of view, this now works. However, the structure tree now is located on the left hand side of the window. This of course is very disturbing.

**Comment by fsbraun** [comment]
Screenshot?

**Comment by jrief** [comment]
here is a screenshot:

<img width="1184" alt="Screenshot 2024-04-26 at 11 31 30" src="https://github.com/django-cms/djangocms-versioning/assets/1132472/fb29d1ad-f3b9-48e9-8e96-e78847e13320">

**Comment by fsbraun** [comment]
The structure board position should be fixed in the now updated build at `git+https://github.com/django-cms/django-cms@release/build`.

**Comment by fsbraun** [comment]
Closed with 4.1.1
